### ISSUE TITLE
Use a bot to handle changes in player lists

### ISSUE THREAD

**Issue by CloneWith** [ppy/osu-wiki#10703]
The player lists (of some groups and tournaments) update frequently, and maintaining their translations is a big challenge, since editing them by hand can cause typos and mistakes.
We have `group-info` files for localization, then a bot can use them to handle list updates, for they are mainly about languages and profile links.

And the update process can be splited into steps:

- Update the English article.
- The bot detects the changes and handle link and language changes automatically. (opening a new PR)
- If other changes exist, mark translations as outdated.

**Comment by cl8n** [comment]
i can do bn and nat pages if https://bn.mappersguild.com/ had complete language info but it currently doesn't (maybe they just aren't required to set it there or something?)

spotlight group maybe

every other group there is no place to get their extra info automatically afaik

**Comment by CloneWith** [comment]
Extra languages are just considered to be **extra** information, for modders mostly use English to mod.

but for user list modification, a bot may help a lot

**Comment by Walavouchey** [comment]
note that the extra information present in user lists are the sole reason they exist. we'd be deleting them otherwise, see https://github.com/ppy/osu-web/issues/9764 and https://github.com/ppy/osu-wiki/issues/2145

that said i'm all for using the bn website. we could tell people to fill out the language info there if they want it changed on the wiki

**Comment by CloneWith** [comment]
yep, that seems better 🐱
