### ISSUE TITLE
Subfolders for official and community tournaments

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1607]
I think the tournaments folder should have subfolders `Official` and `Community`, since community tournaments are filling up.

**Comment by cl8n** [comment]
I think the official ones being called "World Cup" is distinctive enough, imo they all belong under Tournaments/

what do you mean by "filling up"?

**Comment by Joehuu** [comment]
I probably said that because the table of contents and page itself is cluttered. Subfolders won't actually fix that, but just to isolate official from community to make official tournaments have it's own page with content other than listing tournaments. Using abbreviations can also declutter the TOC.

**Comment by cl8n** [comment]
this seems like an issue with any index pages rather than the file tree itself, like i dont think we rly need a "World Cups" article as long as you can visit a general tournaments index and be presented with the World Cups in a section (i think this is already the case)

and then would the Tournaments index just link to Official and Community? that seems like a pointless page

**Comment by Joehuu** [comment]
We can do `Official tournaments` and `Community tournaments`. We had some discussion on discord before (https://discordapp.com/channels/188630481301012481/218677502141399041/486240466585780236).

But on second thought, I'm okay with the structure as-is if others are. Closing as not really an issue.
