### ISSUE TITLE
"The Team" has a lot of different variations

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1698]
First off, is "The Team" a user group? If not, this will only be a consistency problem.

The different variations in wording:
- `The Team` from the article title itself
- `osu! team` from the official tournament articles
- `team osu!` from the osu!dev Discord

Let me say all of them are outdated and/or not used the right way.

- `The Team` article consists of users from the *other* user groups.
- Mentioning `osu! team` from the official tournaments articles is a vague term since not all users in that team are hosting it.
- `team osu!` roles are really outdated and should have whatever people listed on `The Team` article.

**Comment by Repflez** [comment]
The Team is a vague term anyway. There's no distinction on who's on the team or not. This issue is exacerbated since the common knowledge about who's in the team are peppy, people who man the osu!support and those who do administrative tasks.
Initially I thought that changing it to "The osu! Team" would be a nice compromise, but this would need more comments for a term that can be used unambiguously.

**Comment by Joehuu** [comment]
Didn't put this in the OP, but `osu! team` or `osu!team`?

`osu! team` is not a proper noun, and only prefixed with `osu!`.

`osu!team` is a proper noun. This may be the right one.

**Comment by cl8n** [comment]
"osu!team" seems to be a relatively newer term that's used when something is authored by multiple team members, I think it's about the same as "osu!staff"

"the osu! team" would refer to whatever it is that "the team" actually means

either way, it probably doesn't matter too much, maybe we should just choose one way to format this stuff and go with it

**Comment by TicClick** [comment]
now that we have https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team/Account_support_team/en.md, we could use `osu!team` where necessary and link to that article if it's the first mention throughout the page — how about that?

**Comment by peppy** [comment]
I don't really like the "osu!team" term, and would prefer "The osu! team" or similar. Generally we use the "osu!something" for product names and whatnot, not for groups of people

**Comment by TicClick** [comment]
that works. on the other hand, it is diluted when you talk about other teams such as GMT/NAT: they are *osu! teams* (the teams of osu!), but not ***the** osu! teams* (clayton's comment basically). as much as we hate the term "staff", I think it could be of good use in this situation.

**Comment by TicClick** [comment]
on the other hand, we could always paraphrase, or mention *user groups* in case of BN/NAT/GMT/SPT/...

**Comment by peppy** [comment]
i dunno. i'd sooner just assign everyone to an existing team. i think that's the case for 99% already?

**Comment by TicClick** [comment]
it is, except for one case *I think* we are trying to solve, which is referring to people behind the `{accounts,support,whatever-official-and-not-individual}@ppy.sh` addresses.

"the team" is vague, "the osu! team" is overloaded for about the same reason, so "the osu!team" was an attempt to pick a noun that'd clearly state who is meant in which case. it's absolutely not about specific people handling the mails, it's just something short we need to use as a reference to them

and not the support team, because these are the [people looking after Help](https://osu.ppy.sh/groups/22)

**Comment by peppy** [comment]
accounts / support / abuse can just be referred to as the support team (basically the same people with some overlap). unless the idea is to avoid people contacting those people with issues they shouldn't be via PM?

pe@ppy.sh is me
music@ppy.sh can be the licensing team, if required i guess.

**Comment by TicClick** [comment]
ok, *the support team* combined with a link to [the relevant page](https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team/Account_support_team/en.md) should work. I'll make edits where necessary in a few days

**Comment by TicClick** [comment]
I've fixed it where I could, for now the resolution seems to be this:
- use specific team's name where possible (such as in my previous comment)
- use `the osu! team` when you need to refer to people who do "administrative tasks"
- https://github.com/ppy/osu-wiki/tree/master/wiki/People/The_Team/en.md is a successor of [the old Team page](http://web.archive.org/web/20131030005759/osu.ppy.sh/p/team) *("This list is by no means definite, but resembles those in the community which are contributing (or did at one point) outstanding effort towards the project")* and lists contributors, both individual and as separate teams, without strictly saying they are all the core team

if there is anything else to this issue, feel free to reopen
