### ISSUE TITLE
[Critical/ Contributor UX] osu!Wiki Styling Criteria and Contributor Guide needs localizations

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#222]
We have finally set a solid foundation for new standards but to be able for these standards to be understood accordingly, we must consider non-native speakers of English and provide locales for the such.

**Comment by kj415j45** [comment]
WIP: #196 #197

**Comment by sr229** [comment]
CC for localization teams that everyone has, you guys are free to work around with this since we really need this because of the wave of new contributors

**Comment by sr229** [comment]
a year after, we're still pretty much stuck on this issue, with only a few languages supporting the ASC and OWCG. We should probably raise more awareness to promote accessibility for more contributors.

**Comment by cl8n** [comment]
most other languages' translation efforts are hardly existent right now. I really doubt that putting priority on these articles is going to fix that (which may not be possible anyway, because nobody wants to or is available to translate them)

it's also idealistic to assume that people actually use the resources buried in the wiki to learn how to contribute here

**Comment by Krystool** [comment]
Can take the responsibility of FR translation.

**Comment by sr229** [comment]
Looks like we already have progress here so I'm leaving this off as closed as we have finally have the needed localisations.
