### ISSUE TITLE
Tournament match results tables are unlabeled/confusing

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2271]
for most tournaments
- dates are written in the table header for some reason (are dates even needed if they're in the schedule already?)
- table isn't labeled
- nothing describes match links, currently you have to hover over a random "# 1" to tell that it's a match link at all
- double elim brackets aren't specified

**Comment by WalterToro** [comment]
> * dates are written in the table header for some reason (are dates even needed if they're in the schedule already?)

People can think matches are done in the same day when thats not the case, this info carries on from the old wiki and we followed this format unless for old tournaments there is no info about the date of a particular match (because deleted mp link results)

> * table isn't labeled

Probably the last column can be labeled as MP Link?, notes? idk what else to propose.

> * nothing describes match links, currently you have to hover over a random "# 1" to tell that it's a match link at all

Should be resolved with column label

> * double elim brackets aren't specified

This should be the work of a bracket more than the match results i think

**Comment by cl8n** [comment]
- makes sense for dates, but they definitely shouldn't be a header. just normal text above the table or something
- from tournament we just edited i think `| Player 1 / Blue Team | | | Player 2 / Red Team | Match link |` would be good
- ye
- most tournaments dont show a bracket

also forgot to add that the "-forfeit-" or any other note formatting is super weird, that should probably be italics instead of dashes
