### ISSUE TITLE
RFC: Automatically close inactive pull requests/issues

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#2356]
We seem to accumulate some stale PRs at some point in osu-wiki, mainly due to the negligence of the pull request author. I recommend we add [Stale](https://github.com/marketplace/stale) so we can encourage active pull request nature.

**Comment by peppy** [comment]
I don't really think this is required. Probably enough to just have maintainers go through the open PRs once a month or so and close or complete inactive ones (see the lazer repository - you guys are doing fine).

**Comment by cl8n** [comment]
agree with peppy, seems like all of the inactive ones right now are almost complete and a maintainer can make any final changes that are needed. but I'm not sure any of the current maintainers would be willing to do this, afaik the only one that actively contributes content to the wiki anymore is Walter with tournaments

that being said I think @Joehuu and @MegaApplePi would make good maintainers for this purpose if they're up for it /o/

**Comment by sr229** [comment]
My only concern is with some PRs are despite their almost-complete state, most of the authors of these PRs are not responding to us, worse is they've been sitting there for more than 30 days. While we do have maintainers we might encounter a large number of this kinds of PRs that might be more than we can chew, so I think its a consideration when the time comes.

**Comment by Joehuu** [comment]
Reminder that this is a wiki, any content is good if it’s still relevant. And by the looks of it, the PRs over 30 days of activity are mostly translations. We just need translator maintainers.

**Comment by Joehuu** [comment]
We have 15 PRs atm, inactive ones being translations, so this is not an issue.

**Comment by WalterToro** [comment]
Before closing this issue, i think we have people who does reviews, @cl8n @Joehuu @MegaApplePi and @fajar13k (on tournaments) but we need to give people the power to contribute even more because currently @TPGPL and me are the main butan pushers here and sadly my time has been very limited (and the rest of the osu! team helps mainly pushing some news articles and refreshing changes on those)

I did internal proposals for this but to be transparent, i think adding 1-2 contributors could help when this situation comes again, but for now, we did a clean up of the PRs and we have an okay number so better to close this issue and probably we can follow this on the dev discord.
