### ISSUE TITLE
Non-English articles review problem

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-wiki#241]
As we know, new/edit articles here need review~~(except being permitted).~~
But there's a problem: non-English writer/editor sometimes don't have other writer/editor/reviewer to review their article(s).
How to deal with these articles(PR)?

~~A suggestion: add reviewer list to contribution. md~~

**Comment by TPGPL** [comment]
List of particular languages' keepers?

**Comment by sr229** [comment]
Problem with the current state of wiki is fragmentation and oblivious to what languages they understand/read and write. Suggesting to do a organizing members so we know which is which

**Comment by kj415j45** [comment]
emm....Github provide `organization -> team`, but no independent team :p

**Comment by kj415j45** [comment]
but the **main** problem is how to deal with **PR with no one review**

**Comment by MegaApplePi** [comment]
If there is no one to review a pull request, then Repflez can just merge it anyways after a threshold (~1 month?). Merging a pull request doesn't mean that the page is permanently set-in-stone really :/.

Though, having the ability to have people review articles is helpful since reviewers can catch errors that the writer isn't able to catch or tell us if the edit was a joke.

And besides, anyone can fix it in the future again anyways :p.

**Comment by Ephemeralis** [comment]
A 7 day or 14 day grace period for translations with few/no other reviewers seems like a fair compromise between keeping it open and also having the PRs actually go in. Like MegaApple says, it's not like they're permanent even if they do go in.

**Comment by kj415j45** [comment]
I vote for 14 days

**Comment by sr229** [comment]
tbh we've been having some progress on locale teams, since we have working groups per lang rn (seeing @kj415j45 's locale team being the first tbh). Probably close this once we've established everything

**Comment by Joehuu** [comment]
We've been doing the two week period for a while, and translations and translators come and go. There will never be a solid team working as this is a community-based project.
