### ISSUE TITLE
More variety in news topics

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2433]
I'm sorting through the news directory for work on another issue, and it's really apparent how the modern osu!news is basically just announcements, while historically it covered all sorts of things, like
- storyboard(er)/skin/map showcases
- summaries of broader community events - mostly osu!weekly
- interviews
- articles about personal experience to share, like "Commentating Circle-Clicking Competitions" and "Easy Mod: How and Why"
- broader-scoped posts about gaming in general

I had my go at trying to bring this variety back with osu!monthly, but the magazine format requires a whole production that's just way too hard to pull off consistently. one-off articles are more realistic and can still be interesting to a wide audience in the community

just throwing this out there since there are at least a few of us who already spend a lot of time writing/editing on the wiki. "reviving" news could be a fun &rewarding project, and I think there's a lot of potential

**Comment by peppy** [comment]
it would be great to get more news posts. we can definitely consider offering contribution bounty to anyone willing to write quality posts on a per-post basis, too.

**Comment by Pachiru** [comment]
I've messaged Nyquill about helping bringing back osu!weekly format cause it was a great way to get informed from the game and its developpement. However, I didn't have any answers so I don't know if he would be interested in making this alive again, but if he does, I'd gladly help.

**Comment by sr229** [comment]
Have you tried other officials of the news team @Pachiru?

**Comment by Pachiru** [comment]
Yeah I have tried in 2018 to contact HappyStick when Coffee Hour was active, about a concept of twitch-live interviews with chosen mappers to talk about a topic that was familiar to them, but also to know more about the mapper him/herself, where the viewers could ask questions to them directly from the chat, in order to give interaction with them. Sadly, HappyStick didn't answered.  

However, from what I've seen recently, pishifat kinda been doing this with his osu!mapping videos where he invites some mappers and asks them about their concepts, ideas, etc... which was very interesting and I think there is something to exploit on that topic. 

Since I'm not very fluent in english, I'd say I'm more comfortable with doing written things rather than audio ones.

**Comment by sr229** [comment]
I say we can still do written ones as-is, Ars Technica even transcripts their voice interviews into written ones. I can also help with this endeavour if need be.

**Comment by Pachiru** [comment]
I've discussed with Gabe yesterday about the ITW thing I've talked about above in this thread, since he is fluent with English. We'll work on this in details and once we're both okay with the path we wanna take with that project, we'll make a short .pdf file to explain the concept in details and some of the topics we could talk about. 

And sure, if you wanna help us, that could be cool :)

**Comment by cl8n** [comment]
> In the earlier days of the tumblr blog, the QAT Gazette was roughly equal parts "what happened in meetings and what are we (the then-QAT) going to do going forward", and a variety of informational / opinion pieces from members on a topic of interest, e.g. "How to make cool Easy difficulties" or "Observations from the Best of 201X / Community Choice." I think these all got ported to the wiki over time, but in case they didn't, the site still exists here: https://osuqat.tumblr.com/archive
> 
> I think here you're more specifically trying to drill down into the NAT meeting developments, but I noticed #2433 whilst flicking through the list of open Issues and felt like some of the old QAT Gazette ideas (and by extension, some of the stuff you want to do here) might also tick that box.

this is jbh's comment from the issue referenced above, seems more relevant here and that other issue will be closed soon.

**Comment by cl8n** [comment]
related outreach post by ephemeral https://osu.ppy.sh/community/forums/topics/1605337

**Comment by cl8n** [comment]
while not quite what I had in mind when I opened this issue, news content is a lot different & better now. gonna close this issue bc there's not really anything specific that would close it otherwise
