### ISSUE TITLE
User Configuration File needs a rewrite

### ISSUE THREAD

**Issue by yousef157** [ppy/osu-wiki#2480]
Isn't organized like the .cfg file, some commands are missing meanings,
and there are some new commands that aren't in it.

Example: 

![image](https://user-images.githubusercontent.com/48018938/64457889-ef842500-d104-11e9-8f87-8c915867aab3.png)

(means to dim background on breaks)

https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_Program_Files/User_Configuration_File/en.md

**Comment by sr229** [comment]
Is there any other source for this documentation? I might rewrite this if I have the chance.

**Comment by cl8n** [comment]
no, but you can compare the list of properties to your own copy in your game's folder and see what's missing. there shouldn't be a lot to update

**Comment by cl8n** [comment]
looks like the order of the file is user-dependent (because options are added to the bottom when they're changed away from default). it's also hard to verify that all options are present because they aren't listed here if they were never changed from default, and not all of them are accessible from the Options menu in-game

**Comment by cl8n** [comment]
for now I'll just alphabetize the list and add any options that I know for sure are missing, like the background dim on breaks. I'll leave this issue open though
