### ISSUE TITLE
Give the outdated tag more info

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2645]
this is only about usage of the `oudated` tag on translations. english is fine as-is

when a translator sees that an article is outdated and wants to update it, they need to figure out what exactly is "outdated" about it. this isn't super straightforward because
- comparing en to the current language may not be easily possible (if the wording is already significantly different just because of language differences, etc)
- finding the point at which en got ahead can be difficult, and it's not always the same commit (or even the same PR) as when the `outdated` tag was added

to fix this I think we should stop using `outdated` going forward and add `outdated_since`, where the value is the first commit where EN got ahead of this language. then the website's message can include something like "Click here to see what has changed in the original version", linking to a GitHub comparison showing `<commit>..master` for that file

**Comment by cl8n** [comment]
this is a simple addition to the website so I'm just looking for any quick feedback before I try it.

**Comment by sr229** [comment]
I don't think we pull the hash on the cache so its hard to compare something like "This article is outdated by three revisions from English".

**Comment by cl8n** [comment]
that's why you'd write it in the tag. I think I'm misunderstanding your msg ?

**Comment by cl8n** [comment]
added some of these in #2655 because I was going to add comments with the same info anyway. I guess tags that don't do anything yet are the same as comments 💭

**Comment by sr229** [comment]
> that's why you'd write it in the tag. I think I'm misunderstanding your msg ?

I was thinking of doing it automated so yes I think you misunderstood it a bit, but human-based outdated message is better per se.

**Comment by Walavouchey** [comment]
another idea is to have a separate `translation_outdated` tag, since an `outdated` in a translation doesn't distinguish whether the translation is outdated compared to the english version or if the english version is outdated (because the tag is carried over to translations in the latter case).

this separate tag could then be used for [clayton.cc](https://clayton.cc/osu-wiki-status/en) to display if a translation is outdated, so that translators can more easily tell which articles need to be worked on

**Comment by cl8n** [comment]
moved to other issue cuz idk why this was still open
