### ISSUE TITLE
Mention menu-background's (lack of) @2x behavior

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2823]
and probably explain what @ 2x does in more places (each skin elements page... idk)

**Comment by circleen** [comment]
The PR was open?

**Comment by cl8n** [comment]
it didn't make sense, you talked about an "SD size" and "HD size" for menu-background when there is no such thing. you also didn't respond to or do anything about the comment I linked back to 3 times, which said the PR was mostly adding redundant info & not necessary

so this issue supersedes #2756

**Comment by circleen** [comment]
So the entire PR didn't get merged because of one size error?

**Comment by bdach** [comment]
I'm pretty sure it didn't get merged because you didn't address [this comment](https://github.com/ppy/osu-wiki/pull/2759#issuecomment-549015408) (linked for the fourth time, by the way) in any way at all.

For what it's worth I completely agree - `@2x` quite literally means *twice the size* and it's a pretty solidified naming convention, so just explaining it is easier/more future-proof than multiplying everything for people in a bunch of places. Also from my understanding the background "HD resolution" and the other elements' "HD resolution" was not the same thing, since with the background `@2x` just *doesn't work* and you have to make the *normal version* bigger, making your additions even more confusing.

**Comment by RockRoller01** [comment]
menu-background does not have the usual @2x behaviour of needing to be double the size. It instead scales with the screen. However, its technically still possible to use an @2x background. It just pretty useless and a waste of space.
Also, the suggested size shouldnt be 1080p but 1536p, since that is the resolution osu! is based on (or rather its based on 768p for SD)

**Comment by cl8n** [comment]
that doesn't sound any different from the other skin elements then..?

**Comment by cl8n** [comment]
yeah it turns out this was a misunderstanding, there's nothing special about menu-background worth documenting. the default backgrounds also have SD/2x versions as mentioned in last comment
