### ISSUE TITLE
Add yaml key for translations that didn't get a review from native speakers

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2942]
doesn't need to be shown on the website. it'd just be helpful for translators to find stuff to double-check, in case they missed the 14-day window of the PR

**Comment by cl8n** [comment]
@MegaApplePi a lot of things tagged "stale merge" had good reviews from translators, I think you should only add this tag if you merge something with little or no review

**Comment by MegaApplePi** [comment]
@cl8n can you point out an example, or did you already remove the ones you thought were incorrectly tagged? I try to mark "stale merge" if the reviewer did not approve after 14 days since the last activity. Although, there were some cases where this may have been ignored. Usually because I was unsure if the person who approved it was a native speaker.

**Comment by cl8n** [comment]
I already removed them, but yeah the reviewers didn't go back to approve so I guess that's why you added the tag. I checked that the reviews were resolved properly

**Comment by MegaApplePi** [comment]
Alright, I'll try to check for this as well before applying the tag.
