### ISSUE TITLE
Separate <div class> for Team Members in Beatmap Nominators section

### ISSUE THREAD

**Issue by c-sig** [ppy/osu-wiki#3240]
I don't think this will impact the [page](https://osu.ppy.sh/help/wiki/People/The_Team/Beatmap_Nominators) at all but I think using divisions rather than headings make the HTML code look better and in better context.

**Comment by cl8n** [comment]
can you give an example of how you want to change it? I'm not sure I understand

**Comment by c-sig** [comment]
before <h2 id="team-members" class="osu-md__header osu-md__header--2">Team members</h2>, it would be nice to add <div class=team_members> ... </div> to separate it from the others

**Comment by cl8n** [comment]
we're not making markup changes like that if there's no reason, sorry

I'm assuming you want to get the usernames and modes of BNs from this page for your personal project--- you can use the [GitHub Contents API](https://developer.github.com/v3/repos/contents/#get-contents) to get the markdown for this page, or it might be more reliable to scrape https://bn.mappersguild.com/ since the listing there is more up-to-date than this one.
