### ISSUE TITLE
A few incorrect OD values in overall difficulty chart

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [ppy/osu-wiki#3288]
On the OD chart in https://osu.ppy.sh/help/wiki/Beatmap_Editor/Song_Setup#overall-difficulty,
there are 3 incorrect OD values, OD6 + HT, OD9 + HT, and OD9 + EZHT
OD6 + HT should be 3.58, not 3.54
OD9 + HT should be 7.58, not 7.54
OD9 + EZHT should be 1.58, not 1.54
These OD values were calculated by using the 300 hit window given on the chart, OD = (79.5-300hitwindow)/6

**Comment by Icymice** [comment]
I know this is in backlog, but I'm more than happy to redo the table given the values specified are correct

**Comment by cl8n** [comment]
a while ago i was making a sheet to take a new image for these tables, u can request to edit here https://docs.google.com/spreadsheets/d/1qc6EGzL-CZLJGCdNvNb6pcquwuM948A-psDQdh62jvo/edit?usp=sharing

**Comment by Icymice** [comment]
So I should:
- make formatting better
- add the new numbers specified in the issue

I'm not entirely sure what you mean by the 0.5 though so if you could explain that it'd be very helpful.

**Comment by cl8n** [comment]
my spreadsheet has the hit windows as functions of OD and mods so there shouldn't be any mistakes now. I did the formatting changes myself cuz it ended up not taking as long as I thought it would

![od chart](https://user-images.githubusercontent.com/9954349/98398868-7d63e480-2016-11eb-850e-39e516f151f5.png)

notable differences from the current wiki version are the 0.5 differences in hit windows and DT/HT OD values being slightly different due to how the 0.5 scales it around. I think it's more informative to do it this way provided there's a written explanation of what's going on too. the 0.5 comes from how the game uses integer ms for hit times, so rounding can cause you to be outside of a hit window you would've expected to be in

@sometimeszzzzzzz @MegaApplePi do u have any suggestions for this
