### ISSUE TITLE
Number Ranking Criteria rules

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-wiki#3289]
This would make referencing the Ranking Criteria easier and allow for expansion of each rule/guideline into its own article

This would be a first step to making the Ranking Criteria more accessible as per #3143

I've planned to take the lead in this and see that it gets done but would appreciate opinions and discussion on how exactly this should be implemented

**Comment by cl8n** [comment]
not sure what you mean by this, add the symbols where?

**Comment by Pennek** [comment]
Add them before each rule/guideline as a reference point. 

Eg. § 3.1 Hit objects must never be off-screen in 4:3 aspect ratios.

**Comment by peppy** [comment]
Does this symbol have some special meaning? I'm not immediately sure how it improves organisation.

**Comment by cl8n** [comment]
I think the important part of this proposal is the numbering, not the section symbol (not sure that's the correct way to use it)

for referencing i see what u mean bc it's easier to say "RC rule 3.1" instead of a potentially long rule with many exceptions etc... but at the same time, I've personally only seen RC references in places where the explanation of the rule was necessary, like mod discussions

for navigation i dont see how this would help or change anything

**Comment by Pennek** [comment]
The symbol seemed like a good idea to my sleep deprived brain but yes, the numbering is what i think is the most important since it allows referencing rules.

This isnt used much yet, but would allow me to write articles for each rule/suggestion explaining things like: why it exists, examples with images, changelogs to specific rules, etc.

This is the main reason why I think this is a good addition

**Comment by cl8n** [comment]
post to RC forum if you want to see this go anywhere, there are a lot more mappers/modders watching that forum than here

**Comment by Pennek** [comment]
Going to close for now since ranking criteria stuff shouldn't go here
