### ISSUE TITLE
Mapping Techniques

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#429]
#### Creative

- [x] Blanket Combos
- [x] Divebomb Combos
- [x] Flower Combos
- [x] Honeycomb Beats
- [x] Star Formations
- [x] The Kickstream
- [ ] Tornado Combos
- [ ] ztrot Spacing

#### Symmetrical Shapes

- [ ] Circle Formation
- [ ] Diamond Formation
- [ ] Double Stacks
- [ ] QQ Diamonds
- [ ] Reversed Zig-zag Sliders
- [ ] Square Formation
- [ ] Square Formation v2
- [ ] Triangle Beats
- [ ] Zig-Zag Sliders

#### Hit Circle

- [ ] Anti-Jumps
- [ ] Anti-SeibeiStyle-Jumps
- [ ] Center Anti-Jumps
- [ ] Large Jumps
- [ ] Oibon Jumps

#### Slider

- [ ] B&F Sliderbased Jumps
- [ ] Endpoint Slider Jumps
- [ ] Orbital Sliders

#### Spacing

- [ ] 15 Degree Patterns
- [ ] Accelerated Spacing
- [ ] Back and Forth Beats
- [ ] Differential Stacks
- [ ] Drain Sections
- [ ] Half-Backing
- [ ] Hub and Spoke
- [ ] Linear Back and Forth
- [ ] Spacing Out
- [ ] Step-Too-Fars

#### Speed

- [ ] Slider Slowdowns

#### Streams

- [ ] Compressed Streams
- [ ] Discontinuous Streams
- [ ] Deathstreams
- [ ] Slider Stream Jumps
- [ ] Triplet Streams
- [ ] Variable Spaced Streams
- [ ] Zig-Zag Streams

#### Additional Effects

- [ ] Post-Spinner Note
- [ ] Pre-Spinner Note

#### Spinner Variation

- [ ] Double Spinners
- [ ] End Spinner
- [ ] Short Spinners

#### Patterns

- [ ] Etna Sliders
- [ ] Introverted Flow
- [ ] Mirrored Sliders
- [ ] Parallel Sliders
- [ ] Segment Sliders
- [ ] Short Repeating Sliders
- [ ] Slider Trains
- [ ] Zig-Zagging Sliders

#### Stylish

- [ ] Cutting Sliders
- [ ] Crumpled Sliders
- [ ] End-Cutter Sliders
- [ ] Krisom-Krosses
- [ ] Rainbow Sliders
- [ ] Slider Art
- [ ] Spider Sliders
- [ ] Spiral Slider
- [ ] Wave Sliders
- [ ] Windmill Sliders

#### Miscellaneous

- [ ] Switch-Back Sliders
- [ ] Tick-Hitsounds
- [ ] Tricky Triple Combo

### Unrankable

- [ ] Burai Sliders
- [ ] Hold Sliders
- [ ] Ninja Spinners
- [ ] Stack Zero

----

The mapping technique pages are currently missing their images and examples.
What do you guys think about how it should be formatted, how images should be taken, etc.?

---

> formatted

By `formatted`, how should the images be arranged, where should the example beatmaps go? Should I only take screenshots of just a dummy beatmap (no background) with the technique or should I also include the beatmap examples?

/edit will recreate from dummy beatmap and screenshot from beatmap

---

> how images should be taken

By that, should they be `.gif` per 1/4 beat (for all hit objects) or a static `.jpg` (may miss other hit objects)?

/edit will use jpg

**Comment by RaikireHiuduo** [comment]
- If you seriously have the time and motivation, then sure, map it on the dummy beatmap (I do not think anyone would take Mapping Technique that seriously at the first place, since nobody was editing that place for a really long time). Otherwise, a best screencap to show the technique is fine (MT _was based on the forum's MT poll_ anyway).
- Include the beatmap example.

Arrangement suggestion (roughly the same as what I used before I went with the template):-

```Markdown

## MT name

(An image example)

(You can make it a table here if you like but keep the explanation outside of the box unless we have template support)
- Beatmap example + osu! editor timestamp where available:
  - bm1
  - bm2
- Nominator: <-- Can be removed since it is based on forum but your call.

(explanation goes here).

(More image goes here if needed)

```

---

- If you are willing to go through _all_ of the MT, `.gif` example would be nice but would literally kill a player with a limited connection quota.
- If you do not want to deal with all of the MT, the static `.jpg` would be fine provided there is an example beatmap and optionally, the timestamp of the occurrence in the beatmap.

**Comment by MegaApplePi** [comment]
Closing this as discussion has died off and I am not working on this anymore.
