### ISSUE TITLE
.osu file format wiki page seem to be outdated

### ISSUE THREAD

**Issue by Mrcubix** [ppy/osu-wiki#4966]
- For example wiki say hitobjects syntax on index 3 is type, 0 is hit circle and 1 is sliders, except all maps i've looked at never have 0, always 1. 
- no info about objectParams, 
- As far as i know, there isn't option for hitsounds past index 3, except i can see some maps with values superior in a lot of maps.

This is only 3 example out of the section i was interested in making a program, but the whole page might have some outdated values and therefore need changes.

**Comment by cl8n** [comment]
> * no info about objectParams,

it's just a placeholder for the later sections about each hit object, because each object adds a different set of things in place of it. from what I can tell this is documented fine...

> * For example wiki say hitobjects syntax on index 3 is type, 0 is hit circle and 1 is sliders, except all maps i've looked at never have 0, always 1.
> * As far as i know, there isn't option for hitsounds past index 3, except i can see some maps with values superior in a lot of maps.

these numbers (0-7 for type, 0-3 for hitsounds) are bit flags, not values themselves. that's written pretty clear in the Type section too. maybe external link for "bit flags" would help explain?
