### ISSUE TITLE
conflicting information about universal offset and the offset wizard

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu-wiki#5127]
A few months ago I spent considerable amounts of time researching latencies and wrote [this game-agnostic guide](https://github.com/LastExceed/offsets-in-rythmgames). In an email exchange with peppy I got a "looking pretty good!" in response to the guide which made me confident in my knowledge, but 2 days ago I also got a "confused beyond help" in response to [a related issue](https://github.com/ppy/osu-stable-issues/issues/622) so I started double checking my understanding of offsets. I went through the osu!wiki, and the result is that I now actually do feel very confused:
- The "offset" disambiguation page links to [this page](https://osu.ppy.sh/wiki/en/Universal_offset) which explains what UO does, but not why we need it, nor how to measure it, and thus isn't very helpful to the end user
- There is an "offset wizard" in the in-game options, but it shows no instructions on how to use it either. also it seems to be visual even though I was just told that UO is *not* about visual latency
- [The wiki page about the offset wizard](https://osu.ppy.sh/wiki/en/Options/Offset_Wizard) says that UO is for aligning hitsounds, but UO doesn't affect hitsounds at all. And it wouldn't even make sense to me either if it did, as hitsounds aren't predictable (since they are triggered by user input), plus to my understanding UO has nothing to do with input (and I confirmation of this twice in the above linked issue)
- The page about the offset wizard links to a guide about "how to use the offset wizard", but the link is dead the wiki's search function can't find it either. I only managed to find it here on GitHub (it's [here](https://github.com/ppy/osu-wiki/blob/master/wiki/Guides/How_to_Use_the_Offset_Wizard/en.md)). This guide however says that to make the wizard easier to use you need that identically named 2009 beatmap and then proceeds to not use the tool in the options AT ALL. instead it describes a method that again involves user input, and worse yet: a human element
- The beatmap description shows a completely different method that measures a different thing

I also took a look at lazer and got confused even more, because in lazer the offset also affects NC sounds, which isn't the case in stable

---

I'd like to do 2 things:
* Fix this mess. Probably by rewriting most of these wiki pages
* Implement more offsets in lazer (eg video offset)

But before I can do either of those things I need answers to the following questions:

1. My understanding is that "track" refers to the music, and "sample" refers to sounds such as the NC metronome. Is this correct ?
1.1. If yes, why do they desync in the first place ? Aren't both equally affected by audio latency ?
2. Is UO supposed to be used for sample+track synchronization, or for audio latency compensation ?
2.1. In case it's the former, what's the proper way to deal with the latter ?
2.2. In case it's the latter, what's the proper way to deal with the former ?
2.3. In case it's both, how is that possible ?
3. What is the intended way to use the offset wizard ?
3.1. In case the beatmap playing in the background is relevant for this, how can we ever know if it's UO or beatmap timings that need to be changed when each metric requires the other one to already be configured ?
3.2. In case the visuals of the tool are relevant for this, wouldn't that mean the measurement includes video latency ?
4. Why does lazer's offset behave differently compared to stable ?

I understand that the issue I linked got locked because the team doesn't have the time to explain this stuff everytime someone brings up offsets, but in an effort to end this discussion once and for all by making this information more accessible, please help me clear up the confusion

**Comment by peppy** [comment]
1. no. they are played back using different mechanisms. one is streamed; the other is not.
2. it's a catch-all to fine tune, but mostly to synchronise audio playback (which is why the offset wizard tells you to align the beats you hear, not click on screen). compensating for "audio latency" if you mean in the sense of audio-input-response process is not feasible because osu! plays hitsounds. it can be used for this purpose, but using it to compensate more than a small amount will lead to desync somewhere.
3. as above
4. i have no idea what you mean. all samples should be affected by the offset, because it is *applied to the clock*. i already checked stable, but i'm sure lazer is the same too.

as an aside "adding more offsets" is going when you can't understand a single offset is probably a good sign that the average user will also not. keeping it at one, while not completely correct, is at least simple to follow. i won't even get into how this is in some ways not possible and other ways just going to fuck the average user over.

here's the instructions which i would put on a wiki page:

adjust the offset until the GAME FEELS GOOD TO YOU.

that's literally it.

no need to know any technical details.

**Comment by peppy** [comment]
I've removed the guide you linked as it was completely incorrect and I don't know how it got merged.

**Comment by TicClick** [comment]
I think it's a leftover from the Mediawiki times. the existing guides are mostly unrevised

**Comment by LastExceed** [comment]
There are several instances where it took me quite a while to make sense of the wording, so I'm making the following assumptions:

A: The wiki page about UO says ` [...] adds a delay between the currently playing song and the other sounds and graphics associated with it` which is ambiguous due to the lack of an oxford comma. I am assuming that the oxford comma would go after the word "song"

B: You said `This is dealing with audio latency` ([here](https://github.com/ppy/osu-stable-issues/issues/622#issuecomment-806106480)), I assume you only referred to the _relative difference_ in latency between tracks and samples, not to absolute total system audio latency (and especially not input latency as you have stressed many times)

C: I assume your answer to `1.` is referring to `1.1.` in particular and thus implies `1.` to be correct

correct me if I'm wrong

---

2. It becomes feasible when you play without hitsounds, which many players (especially in mania) do for this very reason

3. This doesn't answer my question. I was asking how to use the wizard (as in, what exactly to pay attention to when changing the UO), not just what it's for. This also answers neither `3.1.` nor `3.2.`

4. Simple repro: Listen to [that 2009 beatmap of yours](https://osu.ppy.sh/beatmapsets/4659#osu/24854), with NightCore and NoFail (don't perform any inputs). If your UO is configured to fix track/sample desync, then the NC sounds should be perfectly on beat. Now increase your UO by 100 and listen again. This time the NC sounds will be completely off-beat. But if you do the same thing in lazer, the alignment of the NC sounds won't change. I need to know if this difference is intended/expected, and if yes, why

> it's hard to convey an understanding of a single offset

I don't think so. The main issue is just the amount of misleading, lacking, or just plain false information around, which I am trying to fix here

> the average user will only get confused

With proper UX design this shouldn't be a problem (e.g. hide additional offsets behind a "show advanced offsets" checkbox along with a warning or whatever)

Regarding the guide, nothing prevents us from putting that sentence at the top of the page for the casual player, and then elaborate afterwards for the more invested player

**Comment by LastExceed** [comment]
I'd really appreciate getting a response to this. As it stands now the vast majority of the playerbase is misusing the UO option, without even being aware of that. I want to create proper documentation, but in order to not risk spreading even more misinformation in the process I need someone to confirm or correct my assumptions (`A`, `B`, and `C`) and answer the remaining questions (`3`, `3.1`, `3.2`, and `4`)

**Comment by peppy** [comment]
I don't see this thread going anywhere unfortunately. Maybe you need to test things practically to understand, but I've given up here.

In osu!(lazer) we will aim to make the options self explanatory. Until that happens I'm not elaborating further, beyond my previous post.

**Comment by LastExceed** [comment]
I'm trying to contribute here. Please help me help you.

I have tested practically. And I have described steps to reproduce something that directly conflicts your statement of lazer and stable working the same way. Please don't question my ability of understanding when I point out conflicting information.

> we will aim to make the options self explanatory

im very interested how this is supposed to be possible when you say at the same time that 

> it's hard to convey an understanding of a single offset

unless of course your "self explanatory description" is just

> adjust the offset until the GAME FEELS GOOD TO YOU

but doing this is the very reason why almost everyone is doing it wrong in the first place. it leads to users trying to compensate end-to-end latency, since track/sample desync is insignificantly small in comparison (not to mention that its sole existence is very counter intuitive and probably less than 1% of the community know about it).

**Comment by peppy** [comment]
The wiki pages as they exist are in a fine state. Users can choose to use the offset adjustment as they wish, as long as they feel comfortable. As for future plans, please wait and see. As you mention, there is a discrepancy between stable/lazer implementations and this will likely be addressed in the future. This isn't a current focus and likely won't be for the time being.

Keeping things as simple as possible is an ongoing goal. The current UO can, again, be used by a user as they wish, to account for any single timing issue. Sure, that's not technically correct as you and I have both pointed out, but that is *not relevant* and *out of scope* for the time being. I'm not about to start telling users "Don't adjust UO for input latency issues" because they have no alternative. Until that alternative exists, the single statement of adjusting to make things feel good stands strong. Nothing more needs to be said.

I'm going to tentatively close this issue. You're welcome to PR changes to the guides, but my recommendation would be a footnote mentioning that "while the UO was originally made for music/effect sync, it can also be used to account for other timing issues. feel free to adjust it until gameplay feels good to you."

**Comment by smoogipoo** [comment]
I wrote a document hoping to explain what UO is all about once and for all so these discussions stop coming up: https://gist.github.com/smoogipoo/b2a9b95b4ea258345aaf599e1b47cbb5

You're free to take whatever from that document and reword it/make it into a wiki, but the tl;dr is that UO is all about what feels good for you, as has been said many times before.
