### ISSUE TITLE
Make Contests section more organized and complete

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-wiki#5243]
A reminder that there are a lot of mapping contests now (and in the past), but listing all of them is hard because they are so scattered out (there's not really a consensus to where to post contest announcements in the forum, i've been wanting a dedicated contests subforum for so long) and most of them gets forgotten. i guess feel free to link any contests not yet in the article down in the reply section

The current organization of contest listing is also inconsistent. NPC and PDC gets their winner listing on the main Contests article while others like OBWC and FBC is on a separate article (which just indexes their announcement link)

**Comment by peppy** [comment]
Are you looking for a filter on the contests page here?

**Comment by AncuL001** [comment]
i would also like to suggest having a Contest subforum (like Tournament suforum, but for mapping and such) but it's probably out of scope of wiki

**Comment by Nivalyx** [comment]
yeah, unfortunately this has been the case for more than a year now i'm afraid :( 

both the Contests and the Tournaments article ([#3064](http://github.com/ppy/osu-wiki/issues/3064)) have been reported to be in a dire need of an update/overhaul multiple times before iirc. generally speaking i'm actually interested in taking care of both but as it's something that would obv take up some sufficient amount of time and effort i'll see what i can do

**Comment by AncuL001** [comment]
@Bazzadwarf @Nivalyx you see, the tournaments wiki page is starting to become colossal, and there's no denying that the contest page will follow. i'm proposing a new structure for the entire tournament/contest wiki section. it goes like this for tournament
- the main tournaments page will only link to the home page of each tournaments
- the home page of the tournament will link to each of the tournament iterations
the same applies for contests

this eliminates the need to update the tournaments section every time there's a new iteration of a tournament, reducing update conflicts. the winner tables can also be moved to the home page of the tournaments for a quick summary

**Comment by Bazzadwarf** [comment]
My two cents, I'm only going to speak for tournaments since I am not in the loop with contests.

I agree with the sentiment that the tournament page could eventually become too unwieldy for anyone to reasonably use. Still, I'm not entirely convinced that turning it into a glossary-like page is the correct direction to go in.

In an ideal situation, I'd love to see https://osu.ppy.sh/community/tournaments expanded to handle everything the wiki pages currently do and more, as well as opening it up to community ran tournaments. Still, I understand that it would be a lot of work in `osu-web` for something that a small section of users would use.

I don't have a problem with how the main page is handled, but it is worth keeping in mind for the future.

**Comment by Nivalyx** [comment]
Yeah I second @Bazzadwarf's statement above. 

I think given how disorganized those two pages are before the focus for now should be making the article "organized", "complete", and "coherent" if any (which took us months to complete, as you can see). As with Bazzadwarf : I'm not entirely convinced that turning it into a glossary-like page is the correct direction to go in. but (the suggestion) may be worth keeping in mind for the future.
