### ISSUE TITLE
Update osu!_wiki_Contribution_Guide/Common_Issues

### ISSUE THREAD

**Issue by SiderealArt** [ppy/osu-wiki#5490]
![image](https://user-images.githubusercontent.com/30827929/118492528-aea23780-b752-11eb-9e2b-db6054260199.png)

GitHub added the feature to automatically update forks. Is it still necessary to use the workflow?

**Comment by TicClick** [comment]
generally yes if you want more clean history: if the branch you are fetching has extra commits, this action creates a merge commit on top of it. given that a lot of contributors make changes and pull requests directly in/from `master` (for which I can't blame them, because it really has no relation to the wiki contents itself), there will always be these bits

https://user-images.githubusercontent.com/4686101/118495654-b1396880-b723-11eb-85c0-d507dfd2040b.mov

---

<img width="1262" alt="Screenshot 2021-05-17 at 15 28 29" src="https://user-images.githubusercontent.com/4686101/118496683-a501db00-b724-11eb-9346-1347848abf09.png">

**Comment by TicClick** [comment]
on top of that, you may just want to reset your `master`'s state to that of the original repository, which this button doesn't also help with

**Comment by sr229** [comment]
I'd also like to add, the workflow covers mostly what you would usually use a third party tool for as well (say, Upriver). We'll just document the new upstream button on top of the workflow, but we're not removing it since we need to support really niche and surprisingly common cases such as needing to reset the master in a click of a button.
