### ISSUE TITLE
Add more documentation in the index

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu-wiki#5731]
Would suggest to give more documentation on the "Beatmap submission and ranking" by adding stuffs about VCC, content review, and all of the stuffs regarding mapping that has a wiki page because right now it's quite a struggle to get in there without clicking on a chain of redirection through bunch of pages until getting there

**Comment by TicClick** [comment]
(this issue was about the main page)

I'm gonna go ahead and close this since we have a block with the rules just underneath, with all the regulations mentioned.

a good idea would be incorporating these links into the beatmapping article, though, so that's an extra thing to consider in https://github.com/ppy/osu-wiki/issues/9025
