### ISSUE TITLE
Question: Should "certain" pages be translated?

### ISSUE THREAD

**Issue by user670** [ppy/osu-wiki#583]
By that I mean wiki-contributing-related pages like https://osu.ppy.sh/help/wiki/osu!wiki_contribution_guide . Personally I think those pages shouldn't be translated, and keeping it untranslated can keep non-English speakers away from editing the wiki. What do you think?

**Comment by Deimosu** [comment]
why shouldn't it be translated?

**Comment by kj415j45** [comment]
you're right. If we don't translate owcg, we can *block* people who don't understand English from join osu!wiki. But you can't entirely make them away. Because, actually, they can just add non-English articles (Though it's not good, but allowed).
If we don't translate owcg, it would take them who is willing to contribute twice as much time to understand owcg, it's not good to them.
***
你说的没错，不翻译 owcg 确实能从一开始 *阻止* 无英语能力的玩家加入到 wiki 中，但是你不可能让他们不参与。因为有些文章完全可以只有中文（即完全无视英文，虽然不是很好）。
如果不翻译 owcg ，对于有贡献意图的玩家，他们要花费至少两倍的时间理解 owcg 的要求，这不利于贡献者的体验。
~~你看看你理解上下两部分的用时就能明白这一点，更何况 owcg 是一篇上百行的文章~~

**Comment by Deardrops** [comment]
@kj415j45 think it is necessary to translate `osu-wiki-contribution-guide`. that's it.
By the way, we has plan to translate this page to ZH. While #513 is writing by sb. we have to wait for its completion.

**Comment by user670** [comment]
@kj415j45 However ONLY people that speak English can contribute to the GitHub Wiki since Pull Requests are in English... Back to the years when the wiki used MediaWiki it'd be truly "everybody can contribute".

**Comment by Deardrops** [comment]
@user670 = =！不是这么一回事，使用英文交流是github的传统（github从来没有做过其他语言的本地化），为了就是`任何人（不论使用哪种语言）都可以贡献`。试想，如果我们用中文开issue，中文来讨论，势必会对英语使用者造成很大的困扰，他们无法参加到我们的讨论中，反之则不然。
另外，讨论中文翻译相关的问题我们都是在自己的Discord频道上。小的问题我们可以在频道上讨论出结果来，大的问题我们也会在达成统一意见后通过issue或者其他形式反馈给官方。
欢迎你的加入我们的Discord频道：https://discordapp.com/invite/PjWW8Wg
（可能需要自带梯子

**Comment by user670** [comment]
Well

Closed.
