### ISSUE TITLE
Wiki Standards

### ISSUE THREAD

**Issue by Repflez** [ppy/osu-wiki#6]
Since we don't depend on Mediawiki anymore, we can have more freedom when making articles. Therefore, a new standards for articles should be made to reflect that.

This issue will be used for discussion on the efforts, but joining the [discord chat](https://discord.gg/ppy) is a better option for a more timely answer.

**Comment by RaikireHiuduo** [comment]
Cheatsheet of Markdown language: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

This is a draft styling guide. Need refinement help.

Try to restructure page to GitHub-flavoured Markdown (GFM)-compliance whenever possible unless it affects user page design readability or maintenance readability issues.

## Table of Content
```
i. lowercase-only
ii. replace-space-with-hyphen-'-'

#TOC
1. [myHeader1](#myhead1)
  1. [mySub1](#mySub1)
2. [Header 2](#head-2-here)

# myHeader1 <a name="myhead1"></a>
Hi

## mySub1 <a name="mySub1"></a>
I am

# Header 2 <a name="head-2-here"></a><a name="h2h"></a>
Baymax
```

[GFMTest](#gfmTest "GFM offline testing")

## General styling
```
GitHub-flavoured Markdown (GFM)-specific:-
Headers     : Use '#' styling.
Bold        : **bold**    (double asterisks)
Italics     : _italics_   (single underscore)
Strike      : ~~strike~~  (double tilde)
Bold&Italic : **_BI_**
Quote       : > rhythm is just a "click" away!
Redirect    : [page text](link "Alt text"), or  [page text][my-reference]
                                                ...
                                                [myreference]: http://www.google.com "Omnipotent searchbar"
Image       : (Use HTML tag if size and alignment mattered). Add an exclamation mark, '!', in front.
              [page text](link "Alt text"), or  [page text][my-reference]
                                                ...
                                                [myreference]: http://www.google.com "Omnipotent searchbar"
Unordered   : Use '-' styling.
Ordered     : Use '1./2./3.' styling.
Code        : ```Multiline```, `Single`
Escaping    : Use backslash, \

HTML tags-specific:-
Underline   : <u>underline</u>
Newline     : <br>, or <br />
Redirect    : <a href="link" title="alt-text">Link to other place</a>
Image       : <img src="./img/wikime.jpg" title="wikimeImage" width="200px" height="200px" align="right" />
Unordered   : <ul><li>Bullet point</li></ul>
Ordered     : <ol><li>First</li></ol>
Comment     : <!-- Hidden comment from public view -->

HTML table tags-specific:- (Worst-case scenario)
Bold        : <strong>bold</strong>
Italics     : <em>italics</em>
Code        : <code>std::cout << "Hello World!" << std::endl;</code>
```

## Table styling
Based from #70 :-<br>
Use Markdown table, and use HTML tags inside the Markdown table as necessary (such as `<ul>, <ol>, <br>, <img>, <a>, <span>`). Most of the Markdown will work except the unordered/ordered listing (must use HTML tags, see: https://stackoverflow.com/questions/19950648/how-to-write-lists-inside-a-markdown-table).

Please be reminded that:-
1. the first row should be a header,
2. the second row must be `---|` (triggers GFM's table mode),
3. each table row is separated by a newline,
4. each table column is separated by `|`,
5. output will uses all the space provided,
6. automated column resizing, and
7. use `<br>` or `<br />` if you want a newline behaviour inside the column.
8. Leave a newline empty to escape GFM table mode.

```
Name | Play mode
--- | ---
RH | osu! <br />Catch the Beat
Bob | ~~Taiko~~ _osu!mania_
Anon | Hi!<ul><li>osu!<ul><li>Skill: A</li></ul></li><li>Taiko<ul><li>Skill: B</li></ul></li><li>Catch the Beat<ul><li>Skill: C</li></ul></li><li>osu!mania<ul><li>Skill: B</li></ul></li></ul> **_[My page!](http://osu.ppy.sh/u/1 "Annoying moose")_**

^ For a more extreme version of GFM & HTML hybrid, check out osu!store page and read the RAW version: https://github.com/ppy/osu-wiki/blob/master/wiki/osu!store/en.md
```
Name | Play mode
--- | ---
RH | osu! <br />Catch the Beat
Bob | ~~Taiko~~ _osu!mania_
Anon | Hi!<ul><li>osu!<ul><li>Skill: A</li></ul></li><li>Taiko<ul><li>Skill: B</li></ul></li><li>Catch the Beat<ul><li>Skill: C</li></ul></li><li>osu!mania<ul><li>Skill: B</li></ul></li></ul> **_[My page!](http://osu.ppy.sh/u/1 "Annoying moose")_**

^ For a more extreme version of GFM & HTML hybrid, check out osu!store page and read the RAW version: https://github.com/ppy/osu-wiki/blob/master/wiki/osu!store/en.md

In worst case scenario (such as the need of using width/height/forced column width/colspan/rowspan/excessive use of list with children list and grandchildren list, and/or _children table_ inside a table/extremely-specific table attribute was needed), use HTML table along with proper sanitisation (a lot of character escaping will be needed). If possible, restructure to avoid the use even at the cost of more space usage (leading to more scrolling), because raw HTML for table is extremely syntax-heavy (GFM will not work, all HTML tags only) to maintain and prone to security errors for most writers with rudimentary understanding.

No idea about the standard for raw HTML other than the basic structure tags needed (`<table>, <tr>, <td>, <th>`) and must do special characters escape. Indent is optional but appreciated for readability.

## Images
Image display on the page:-
- Use Markdown if the image has been optimised and can be used as is.
- Use HTML's img tag if need to resize/align on-the-spot and need to preserve the original image size as is.

Image storage:-<br />
- Currently, some images are scattered (see: difficulties) around the pages and some reside in 'shared' folder.

Image storage suggestions:-
1. Put images to 'shared' folder, and images stored into page name's folder it should appear in.
2. Make an 'img' folder on the page filepath on-the-spot and put the images inside the 'img' folder.

Currently, I have no idea about all the images from the MediaWiki by time of writing.

## Keyword directory linking
I am assuming the fact that the file structure right now is not a permanent file structure.
- Reference style preferred.
- Absolute linking from root to source (I generally prefer relative linking unless I need to go back to previous directory for more than once).
- Use Markdown linkage for page traversal (except for raw HTML table).
- Refer to "Images" section above for images.

## Reusable templates
No idea.

## Navigation bar
Waiting for new wiki's user front-page prototype.

## GFM offline testing <a name="gfmTest"></a>
Markdown highlighting:-
1. Github's Atom.
2. StackEdit.
3. Any text editor of your choice and their plugin/modules to support GFM highlighting.

Live display:-
1. GitHub's Atom. (Shortcut: CTRL-SHIFT-M)
2. Markdown Preview Plus (Google Chrome) / Markdown Viewer (Mozilla Firefox)
3. StackEdit (Limited)

Source: https://stackoverflow.com/questions/9843609/view-markdown-files-offline/

---
This comment in downloadable tidy .txt format: [stylingDraft.txt](https://github.com/ppy/osu-wiki/files/643622/stylingDraft.txt)

**Comment by MegaApplePi** [comment]
> No idea about the standard for raw HTML other than the basic structure tags needed (`<table>, <tr>, <td>, <th>`) and must do special characters escape. Indent is optional but appreciated for readability.

I would suggest to use the `<thead>` and `<tbody>` tags as well.

Also, what do you mean by "special characters escape"?

----

It _should_ probably look like this:

- Using `<table>`, `<thead>`, `<tbody>`, `<tr>`, `<th>`, and `<td>` tags

```html
<table>
 <thead>
  <tr>
   <th>Player 1</th>
   <th>Player 2</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>You</td>
   <td>Me</td>
  </tr>
  <tr>
   <td>1st</td>
   <td>2nd</td>
  </tr>
  <tr>
   <td>90 pts</td>
   <td>89 pts</td>
  </tr>
 </tbody>
</table>
```
<table>
 <thead>
  <tr>
   <th>Player 1</th>
   <th>Player 2</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>You</td>
   <td>Me</td>
  </tr>
  <tr>
   <td>1st</td>
   <td>2nd</td>
  </tr>
  <tr>
   <td>90 pts</td>
   <td>89 pts</td>
  </tr>
 </tbody>
</table>

----

- Same as above but without the `<thead>` and `<tbody>` tags

```html
<table>
 <tr>
  <th>Player 1</th>
  <th>Player 2</th>
 </tr>
 <tr>
  <td>You</td>
  <td>Me</td>
 </tr>
 <tr>
  <td>1st</td>
  <td>2nd</td>
 </tr>
 <tr>
  <td>90 pts</td>
  <td>89 pts</td>
 </tr>
</table>
```

<table>
 <tr>
  <th>Player 1</th>
  <th>Player 2</th>
 </tr>
 <tr>
  <td>You</td>
  <td>Me</td>
 </tr>
 <tr>
  <td>1st</td>
  <td>2nd</td>
 </tr>
 <tr>
  <td>90 pts</td>
  <td>89 pts</td>
 </tr>
</table>

**Comment by MegaApplePi** [comment]
Partly from the dev chat, to represent a key on the keyboard, enclose the key with grave accents (<code>&grave;</code>). Don't use the `<kbd>` tag.

i.e. ```You can use your mouse buttons or the `Z` and `X` keys on your keyboard to click.```
You can use your mouse buttons or the `Z` and `X` keys on your keyboard to click.

Just as a general suggestion for consistency, use capital letters, like `Y`, `F12`, `*`, `ESC`, `CTRL`, or `ALT`.

Note that some articles in the old wiki had enclosed the keyboard keys with square brackets <code>[</code> and <code>]</code>. Don't use this anymore and use the grave accents instead.

**Comment by peppy** [comment]
I believe for keys we should use the same case as found on most keyboards. Capital letters for single characters, but CamelCase for function keys.

`O` `S` `U` `Ctrl` `Alt` `PrtScn`

**Comment by TPGPL** [comment]
Probably close this one?

**Comment by Repflez** [comment]
This is more of a long term discussion place, though...

**Comment by peppy** [comment]
Anything which should be referenced to on an on-going basis should probably be migrated to an actual wiki page. You may want to consider making a wiki standards page if that doesn't exist yet (if it seems like a valuable thing to have around).

**Comment by sr229** [comment]
Isn't ASG the actual Wiki Standards @peppy?

**Comment by peppy** [comment]
what is ASG?

**Comment by Repflez** [comment]
@peppy **A**rticle **S**tyle **G**uide.

**Comment by peppy** [comment]
i see! found it now (a link would have been helpful - [here's one](https://new.ppy.sh/wiki/Article_Style_Guide/) for future visitors).
