### ISSUE TITLE
Known issues (in hindsight)

### ISSUE THREAD

**Issue by RaikireHiuduo** [ppy/osu-wiki#69]
Current known issues (features not found/unsupported/not yet implemented):-
1. No templates support.
1.1. No directory bar/box
2. GitHub's Markdown language for table does not support colspan/rowspan (?). [Minor issue, probably, just rewrite it to raw HTML's table].
3. No public front page (yet).
4. No TOC (Table of Contents).
5. Keeping image history. Example: https://osu.ppy.sh/wiki/File:Multi-play.png
5.1. Keeping the page history.

Trivial question:-
1. Why migrate to GitHub?

---
May take a while for me to get used to GitHub. Expect no progress for now in GitHub as I experiment (I have no clue what am I doing. Very likely I may do hybrid raw HTML and Markdown as see fit).

**Comment by LiquidPL** [comment]
>1. No templates support.
  1.1. No directory bar/box
>2. GitHub's Markdown language for table does not support colspan/rowspan (?). [Minor issue, probably, just rewrite it to raw HTML's table].
>3. No public front page (yet).
>4. No TOC (Table of Contents).

The wiki is not going to be browsed in GitHub finally. It is going to be browsed on the new osu! website (implementation pending) which will load the articles from GitHub and also (probably, not sure if those are planned) will handle stuff like templates, and the front page.

>5. Keeping image history. Example: https://osu.ppy.sh/wiki/File:Multi-play.png
  5.1. Keeping the page history.

Ever heard of something called a version control system. Git/GitHub is one of them.

**Comment by cl8n** [comment]
Yeah, I think it's safe to do away with the on-site versioning entirely now that it's hosted on GitHub anyways.

Certain templates and pages like the front page can be handled entirely on-site, and that's no problem. Table of contents boxes can be generated dynamically as the wiki changes. The issue here with templating is that markdown doesn't directly support any sort of template system, so if we were to make and handle templates, editors would just need to know how to use them and rely on the template reference to see how they look in files.

To be honest, I don't think there are any super straightforward answers here. The route that comes to mind for me is just rebuilding an editor that users can have access to on-site, and adding this sort of structure:
- Let users log in with GitHub and make branches / commit things to their fork on-site, along with a link like "Open a pull request" when they made changes (does the GitHub API even allow this?)
- Add a "template" folder at the top level of this repository, next to "wiki"
- Make up some fancy syntax that the website can use to call templates with arguments by name from "template"
- More fancy syntax to use within templates for arguments

This would just be going full-circle back to what MediaWiki was, though. And it'd be a massive increase of effort for the web developers. Also you'd have to say goodbye to doing most work locally...

I don't know why we switched the GitHub in the first place, but it seems to be going well so far.

**Comment by MillhioreF** [comment]
IIRC there's not going to be any sort of on-site editor, and edit links will just lead to GitHub and require users to supply their own accounts. I'm not sure if that's still the current plan, but it does make things simpler and raise the barrier to entry, which is probably a good thing honestly.

The other advantage is that MediaWiki has abysmal performance, so getting rid of it would be a great blessing to the backend. Having to reimplement templates does kinda hurt, though.
