### ISSUE TITLE
Add new tag to distinguish outdated translations from outdated base article

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#7383]
> another idea is to have a separate `translation_outdated` tag, since an `outdated` in a translation doesn't distinguish whether the translation is outdated compared to the english version or if the english version is outdated (because the tag is carried over to translations in the latter case).
>
> this separate tag could then be used for [clayton.cc](https://clayton.cc/osu-wiki-status/en) to display if a translation is outdated, so that translators can more easily tell which articles need to be worked on

_Originally posted by @Walavouchey in https://github.com/ppy/osu-wiki/issues/2645#issuecomment-1137786144_

**Comment by cl8n** [comment]
the original idea was that translations would be marked `outdated` *only* if it were for the translation's status, but as you noted:

> the tag is carried over to translations

and this was more for osu-web limitation bc inter-article dependencies at update time would add a lot of complexity

it's probably fine for now to just make a new tag though.

**Comment by DoryanR** [comment]
In my opinion as a translator, it would be a good idea to keep the current way of working, with the use of the `outdated` and `outdated_since` tag, even if I find that `outdated_since` doesn't make much sense when the article is outdated since a long time, because only the hash of the article that will have put the tag will be put, and not the potential future updates of the original article (if I understand the way it works). You'd have to make a history of the hashes where the original article has been updated, so that it can be used as a reference for those who have to update it later, without necessarily checking each line by hand.

And indeed, when the original article is outdated, and the translated article must also have this tag, another additional tag like the one proposed (`translation_outdated`), with separation of the listing on clayton.cc, would allow to really know which article is really outdated.

Then, I think that at clayton.cc level, it would not be bad to modify the lists, and make a `Outdated (up to date with en.md)` list, `Outdated with en.md` list in order to follow the logic of what I am saying.

This is only my opinion, but it would be a great progress for the follow-up of the translators, especially as in our case, the French ones, where we are at the point of sorting out the really outdated articles and the outdated but up to date with the English version.

**Comment by cl8n** [comment]
> You'd have to make a history of the hashes where the original article has been updated, so that it can be used as a reference for those who have to update it later

use a range in git from `<outdated_since>^` to `master`. this is the command osu-wiki-status uses to get the diff for each article:
```sh
git diff "${article.outdated_since}^...master" -- "wiki/${article.path}/en.md"
```

**Comment by Walavouchey** [comment]
> In my opinion as a translator, it would be a good idea to keep the current way of working, with the use of the outdated and outdated_since tag

to make things clear:

- english article
  - content is outdated?
    - `outdated`
- translation
  - english content is outdated?
    - `outdated`
  - translation is outdated?
    - `translation_outdated` and `outdated_since`

we'll need a new tag because `outdated` needs to be carried over to translations due to osu-web reasons, as [clayton explained](https://github.com/ppy/osu-wiki/issues/7383#issuecomment-1137875034)

> make a Outdated (up to date with en.md) list, Outdated with en.md list in order to follow the logic of what I am saying.

in clayton.cc, the "outdated" list would use `outdated` for english articles, and `translation_outdated` for translations. if you want to know whether the content is outdated, just check the english version. having both types of lists when looking at translations would be redundant
