### ISSUE TITLE
Add dimensions to newspost banner

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-wiki#7501]
this page doesn't list the dimensions (2000 x 400) for newspost banner, really should be on here https://osu.ppy.sh/wiki/en/News_styling_criteria

it also isnt really searchable nicely, probably should add tags like "newspost banner" or "banner" in general

**Comment by TicClick** [comment]
perhaps the criteria may be refreshed as well https://github.com/ppy/osu-wiki/blob/master/wiki/News_styling_criteria/en.md?plain=1#L1=

**Comment by cl8n** [comment]
banner should be whatever size scales best in most areas of the website for your image. it doesn't have to be 2000 x 400 (where did these numbers come from?)

**Comment by RockRoller01** [comment]
these are the numbers i got from ephemeral and just earlier today got them from him again when asking for them as i couldnt find them.

and yes, the image scales and it depends on the end device what is visible, so technically no fixed dimension would be needed, probably would still be best tho to unify it?

**Comment by cl8n** [comment]
depending on the content of the image you might want it to be taller or wider so that more of the main graphic is shown at all times, I don't think a static size or aspect ratio would be good here

a recommended minimum should be fine though, for reference here is all the places you'd find it on the website rn (some of these can scale their width down to 0 as device width gets smaller)

- 530x130
- 900x130
- 670x160
- 880x160
- 670x200
- 880x200
