### ISSUE TITLE
Improvements for Discord server pages

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-wiki#8194]
These are some things I noticed with the discord server pages that bother me:

- [ ] they are missing from the index
- [ ] listing discord accounts make it look like a mess, not to mention some people change their handles quite often so idk if its a good idea to list them at all, or maybe only for some tiers like owner & admins
![grafik](https://user-images.githubusercontent.com/35633093/195172763-f2c29f9e-b8f2-424b-a42e-ee851e7c39c7.png)
- [ ] the links in the info boxes just look bad and it seems redundant to me to have the second word (channel, handle, etc)
![grafik](https://user-images.githubusercontent.com/35633093/195174537-201d7c5b-1d13-43ce-bac7-7a33db343415.png)
Think the following would be better to change to an inline list format (which also has the advantage of shortening the infobox, removing a lot of blank space from the page):
![grafik](https://user-images.githubusercontent.com/35633093/195174258-360991e7-0ca9-4813-b8bd-846c4b081fb1.png)
- [ ] this probably goes for any place in the wiki where dates are listed, but seeing a big list of dates looks more like a dataset, rather than something that is actually meant to be read
![grafik](https://user-images.githubusercontent.com/35633093/195175321-ef7b2f64-aa14-46a9-81ac-9c585efbe85f.png)

**Comment by minusQuantumNeko** [comment]
I'd say we need some rules in general, what servers can get there, and how should articles about them be styled. 
But I can't totally agree with your statement that:
> listing discord accounts make it look like a mess, not to mention some people change their handles quite often so idk if its a good idea to list them at all, or maybe only for some tiers like owner & admins

In my opinion it should be decided case-by-case if you list full staff list or not, and what to do in cases like `osu! University`! 
For example, `osu! Medal Hunters` server barely changes its staff, and it doesn't have a big list of staffs. But for servers with often changes of staff or just big list in general I'd suggest to write something like: "`For full staff list, check server channel #staff-listing`"!

Another thing I'd like to share my opinion about is `Events` part of `osu! University` article! I'm not really sure if it should even be there, or should servers list their events on server itself, instead of article! And if events can be listed in article, which ones should go there and what shouldn't!

**Comment by RockRoller01** [comment]
> I'd say we need some rules in general, what servers can get there, and how should articles about them be styled.
Talk about this already happened in the original thread, but yea, a "how to apply" or should be added to the index page of the discord server list probably.

**Comment by TicClick** [comment]
irrelevant due to https://github.com/ppy/osu-wiki/issues/9934
