### ISSUE TITLE
Missing description for DateTime

### ISSUE THREAD

**Issue by Awlexus** [ppy/osu-wiki#835]
The data type DateTime is missing from the [DB file description](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_File_Formats/Db_(file_format)/en.md#user-content-data-types)

**Comment by kj415j45** [comment]
why not try to add it by yourself?

**Comment by Awlexus** [comment]
I tried, but I don't know exactly how it's composed.
I don't want to add wrong pieces of information to the wiki

**Comment by osuShiro** [comment]
If someone can give me details on how DateTime is composed, I'll push a PR to add it.

**Comment by DorJoogl** [comment]
This issue may already be old, but I was wondering the same like Awlexus. I was digging around some. And since the osu! client is written in C#, it suggests that DateTime in the docs may be a binary representation of the [DateTime object in C#](https://referencesource.microsoft.com/#mscorlib/system/datetime.cs). This would make sense because the field is eight bytes long and the `ToBinary` method in the DateTime class returns a 64 bit integer. The integer produced by that function is, to my understanding, built as follows. 

The lowest 62 bits represent the stored Windows ticks. That's the amount of 100-nanosecond intervals since midnight, January 1st 0001 [as pointed out by the .NET docs](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=netframework-4.7.2#remarks). The highest two bits make up the so called local flag.

The local flag is needed if a DateTime instance is explicitly marked as storing a local time. If that's the case, then `ToBinary` will add or remove the time zone offset to UTC in ticks from the ticks field. Additionally, it sets the flag to one. That's pointed out in the source code too.

> As such the format for local times changes to **store the ticks of the UTC time, but with flags that look like a local date**. (see [here](https://referencesource.microsoft.com/#mscorlib/system/datetime.cs,711))

So what that's saying is that the highest two bits only serve a representation purpose if a machine that needs to parse/serialize a DateTime object is not in UTC. Furthermore, the docs explicitly mention that Windows ticks are always represented in UTC. 

> The value of this property represents the number of 100-nanosecond intervals that have elapsed since 12:00:00 midnight, January 1, 0001 (**0:00:00 UTC on January 1, 0001**, in the Gregorian calendar), which represents DateTime.MinValue. (see [here](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=netframework-4.7.2#remarks))

It means that, to my understanding, you would only need to get the first 62 bits of the DateTime field. That's your amount of Windows ticks in UTC. Convert it to a data representation that's more to your liking and you're good to go.

I've no mean of verifying this because the only field that uses DateTime is the "account unlock time" field. And since my account is (luckily) not banned, that field is filled with just zeros. But it's the best guess I can make based on the .NET docs and my understanding of C#.

**Comment by cl8n** [comment]
the DateTime kind is UTC, so you can just read all 64 bits as the amount of ticks

**Comment by DorJoogl** [comment]
That's good to know. So all it needs is a change stating that the DateTime field should be read as an amount of ticks. I can push a PR if wanted. Would just be good to know how to format it. Special section under the "osu!.db format" table? Extra row in the "format" table?

**Comment by cl8n** [comment]
an extra row in the Data Types table
