### ISSUE TITLE
Discussion: What is an osu! original track?

### ISSUE THREAD

**Issue by MChecaH** [ppy/osu-wiki#8807]
There seems to be a lack of clarity on what kind of content should be considered `osu! original` as seen in an [earlier discussion in the dev server](https://discord.com/channels/188630481301012481/218677502141399041/1075320623758315591).

The idea of this post is to clean up the definition and break the apparent ambiguity of this term. These are a few of the interpretations that could be given:

Should it necessarily be Licensed for the track to be Original?
> Ephemeral — Today at 8:46 AM
if we're counting community-made stuff in that label it should only also be the things we've licensed i guess

Should it only need official endorsement without the need of being Licensed?
> Walavouchey — Today at 8:47 AM
that axes about all of the "standalone beatmap releases" and basically all the community tournament custom songs

Can it just be any user generated track without the need of being featured in officially endorsed contest/tournaments/projects...?
> RandomeLoL — Today at 8:47 AM
Cant just be a grafted song made by a community member to be awarded that label (Ex: https://osu.ppy.sh/beatmapsets/1359629#mania/2813453 )

Or even a more extreme case, should this label be **exclusive** to the beatmaps that were made out of the commissioned tracks?

See also https://github.com/ppy/osu-web/issues/9864 which requires of this discussion to narrow the scope of the category.

**Comment by peppy** [comment]
It should be anything commissioned by us, or anything made and released exclusively on osu!, where we can obtain a written statement from the user that they are okay with the track being listed under the category and used within osu! for free.

**Comment by Walavouchey** [comment]
> It should be anything commissioned by us, or anything made and released exclusively on osu!

that is basically equivalent to the current wording:

> **osu! originals** are songs that are specifically made for (or otherwise first premiered in) osu! or other osu!-related events such as tournaments, contests, and [Featured Artist](/wiki/Featured_Artists) announcements.

![image](https://user-images.githubusercontent.com/36758269/219041383-0579516d-20fc-42b8-b069-4c4c41df1249.png)

there have been instances where we've had to ask the artist whether a song was made specifically for osu!, but most of the time this is easy to see (e.g. part of mapping project, artist made the map along with the track, etc.)

> okay with the track being listed under the category and used within osu! for free.

except for this part. you'd have to ask most artists listed in the "osu! originals" wiki page about this. (not sure if you meant it that way)

it would basically call everything from <https://osu.ppy.sh/wiki/en/osu!_originals#community-run-tournament-releases> and below into question, as well as some tracks included in official tournaments since some of them weren't actually commissioned.

---

if we go with this, then i'd be down for going around to ask

**Comment by mangomizer** [comment]
> note that some tracks commissioned by osu! aren't on the featured artist catalogue, implying that they're not licensed as such... ? (e.g. [katagiri - Buta Musou](https://osu.ppy.sh/beatmapsets/1884920) ([soundcloud](https://soundcloud.com/katagiri/buta-musou)) or [NIWASHI - Harder Than Diamond](https://osu.ppy.sh/beatmapsets/1884920) ([youtube](https://www.youtube.com/watch?v=PCc2tM3YWs0)))

In the case of katagiri - Buta Musou, it was privately commissioned (not by osu!). Permissions were obtained to create the remix, but I think we would run into a few troubles if we tried to license it.

In the case of NIWASHI - Harder than Diamond, there is a reason for this (it will be added eventually).

**Comment by Walavouchey** [comment]
> It seems silly to label an unlicensed song as an osu!original. Likewise, it would be equally silly to retroactively apply the tag to songs that were released already (how can something become original after its release?)

you mean released for osu! specifically? all tracks in the wiki page satisfy this point. custom-made community tournament tracks also satisfy the licensing part, except that they're not licensed by the osu! team specifically.

"osu! original" wasn't even a term before 2021 (it was added in https://github.com/ppy/osu-web/pull/8081), and was originally "osu! exclusive" (https://github.com/nanaya/osu-web/commit/cfa116dec9b0a6207636adf0c22032872a1f0900) since only 2016, so e.g. [nekodex - new beginnings](https://osu.ppy.sh/beatmapsets/1011011) would need its label removed

> licensed to osu! (official) and only osu! prior to its debut. [...] how can something become original after its release?

they already originated from the game - we just hadn't put the label on them. e.g. most of these tracks didn't have any sort of label when they were first released.

![image](https://user-images.githubusercontent.com/36758269/219073034-88410e75-1e45-466c-af97-c3c5e32038e5.png)

**Comment by mangomizer** [comment]
assume "osu! team" interchangeable with "osu! official "

> custom-made community tournament tracks also satisfy the licensing part, except that they're not licensed by the osu! team specifically.

I do specifically mean licensed by osu! team. It may not be desirable to label all community made tracks as osu!originals, as the content may not align with the vision/ethos of the osu! team. Admittedly this scenario is highly unlikely, but I've previously had to ask an artist to rename their original composition because the title was inappropriate for the community.

If the goal is to only have "ORIGINAL" as a single label (desirable imo, as it reduces obfuscation/the need for multiple labels), and this label is being applied to songs in the listing, then it would naturally only be applicable to tracks which are licensed to the osu! team.

> "osu! original" wasn't even a term before 2021 (it was added in https://github.com/ppy/osu-web/pull/8081), and was originally "osu! exclusive" (https://github.com/nanaya/osu-web/commit/cfa116dec9b0a6207636adf0c22032872a1f0900) since only 2016, so e.g. [nekodex - new beginnings](https://osu.ppy.sh/beatmapsets/1011011) would need its label removed

I was the one who suggested the change from osu! exclusive -> osu! original as I noticed the possibility of a misconception in which osu! licensing is exclusive (it never is). The change is in name only, but the function of the title remains unchanged.

> licensed to osu! (official) and only osu! prior to its debut. [...] how can something become original after its release? 
> they already originated from the game - we just hadn't put the label on them. e.g. most of these tracks didn't have any sort of label when they were first released.

OK I wasn't really thinking when I typed this. Yes this makes sense, and things can and should absolutely be retroactively applied but only if they are licensed to the osu! team imo.

**Comment by Walavouchey** [comment]
my argument for including community-made tracks is that osu! is otherwise entirely community-driven (aren't ranked beatmaps "official content"?), so i don't see why this label of originality should be limited to commissions made by only the osu! team.

if "non-licensed" originals are the only issue then i'd happily go with [peppy's definition above](https://github.com/ppy/osu-wiki/issues/8807#issuecomment-1431048142)

> the content may not align with the vision/ethos of the osu! team

if it doesn't go against community rules, song content rules, etc. wouldn't it be fair game? even if such tracks existed (and the offending parts were left unchanged for some reason), they'd be [removed from the website](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules#what-happens-if-my-track-isn't-okay?)

**Comment by mangomizer** [comment]
Yeah that's fair. I can agree with community-made tracks attaining original status but only if they have been licensed by the osu! team first.

**Comment by peppy** [comment]
I wasn't looking for discussion on what the term should mean but giving my hard guidelines for it FWIW.

Where it's obvious the track was part of an osu! project (created for it as a remix or otherwise) using it there without explicitly confirming is fine, until it becomes an issue.

The only alternative would be removing from all non-FA tracks across the board (and keeping it as a FA sub-category), which doesn't seem to match its expected scope.

**Comment by Walavouchey** [comment]
> It should be anything commissioned by us, or anything made and released exclusively on osu!, where we can obtain a written statement from the user that they are okay with the track being listed under the category and used within osu! for free.
> [...]
> I wasn't looking for discussion on what the term should mean but giving my hard guidelines for it FWIW.

I think the path forward is pretty clear then, which is to get explicit permission for community-made tracks as a form of licence.

i do want to know what @peppy thinks about "meme" tracks being part of "osu! originals", such as

-  [Jar - ztrout's Visit to The Proctologist](https://osu.ppy.sh/beatmapsets/21145#osu/73546) (original song for a map)
- [happy30 - wob wob](https://osu.ppy.sh/beatmapsets/115621#osu/300814) (original song for a map)
- [osu! training man - TRAINING-1](https://osu.ppy.sh/beatmapsets/1727804) (original song for a map)
- [Boaz Sound Team "ptar124" - How do you pronounce Boaz?](https://www.youtube.com/watch?v=WuSv1zFpAmE) (original song for mapping contest)

there's nothing theoretically barring these from being included if the artists are ok with it. for now all of the ones that have been added are non-graveyarded though.

**Comment by peppy** [comment]
I think it is fine to include them under the definition, yes.

**Comment by peppy** [comment]
Give an example where a song was "made for osu" but would not be implicitly allowed to be used on osu! without asking. I'm a bit confused. 

> Where it's obvious the track was part of an osu! project (created for it as a remix or otherwise) using it there without explicitly confirming is fine, until it becomes an issue.

This is what I said above as well. If something was made on the platform, then unless the artist comes back and requests something otherwise, I think it comes with the implication that it can be used.

**Comment by Walavouchey** [comment]
"made for osu!" is the simple definition that all currently listed originals satisfy. so far it's been taken very literally, but may come with some caveats.

- > okay with the track being listed under the category

  there has been at least one artist that initially was questioning of the idea of including a "joke song" in the "osu! originals" listing
  
  there's no requirement for quality or anything. so far the reasoning has been that "osu! original" is more of a category of maps, not an official stamp/label, meaning anything that fits the the definition of being "made specifically for or first premiered in osu!" is listed

- > used within osu! for free.

  should "made for a specific beatmap" (tournament, standalone map, contest entry, etc.) be assumed to imply "allowed to be used in other beatmaps"?

  it's not explicitly specified, which is why this disclaimer exists:

  ![image](https://user-images.githubusercontent.com/36758269/223343035-71d7f9bc-1ec5-4cf1-adff-1f1aafa16c7e.png)

  i mean, this can be solved by asking "hey can this song be used in other maps etc." which wouldn't be hard to do for almost all songs listed

**Comment by Walavouchey** [comment]
given the lack of further discussion, i'm going to consider this resolved for now with the conclusion that no change to the scope or definition is necessary.

**Comment by mangomizer** [comment]
My issue with the current implementation is that the wiki term osu! original and the ORIGINAL tag do not have the same definition.

After giving it some thought, I would like to propose the following as I believe it would improve clarity for all. 

My proposal:
- Change osu! original -> osu!original to make it an osu! official branding and protected term. ORIGINAL tag would be made synonymous with this.
- Apply osu!original only to tracks that are commissioned by the osu!team. This would include soundtracks as well (eg. nekodex - circles!).
- Split the existing wiki page into two - "osu!originals" and "original songs from community events".

Reasoning:
- Achieves parity with the osu!original wiki page and ORIGINAL tag. 
- Restricting the label to osu!team commissions would mean that only "official releases" get tagged. This is ideal because:
  - Only official releases are guaranteed to have non-exclusive usage rights in the game. Most community released original content is probably OK to use but likely no formal agreement. Feels inappropriate to call them "osu!" original if they potentially cannot be used freely on osu!
  - Easier maintenance, never need to be retroactively apply an ORIGINAL tag for community originals that were subsequently licensed (even today there are some that are missing under the current definition).
  - There will never need to be a discussion on whether a song "counts" as an osu! original. This is especially useful if a song is meme-tier or confusing use case. These can easily just go into the other wiki page.

**Comment by mangomizer** [comment]
On subsequent discussion with Wala it is probably better to retroactively include licensed originals from the community for acknowledgement and just to be more encompassing in general.
