### ISSUE TITLE
Complete tags of wiki articles

### ISSUE THREAD

**Issue by CloneWith** [ppy/osu-wiki#9673]
Now tags are used in searching, functioning by figuring out keywords of articles.

- Currently some articles don't have tags, do we need to complete them? (or no tag is enough)
- I feel difficulty searching in native language (like Chinese), for it split the word into each character. What if we give more priority to tags in one's native language?

![image](https://github.com/ppy/osu-wiki/assets/110881926/6bb5437a-83bb-4105-8697-2533987099b1)

**Comment by sr229** [comment]
CC @Walavouchey @TicClick, I think we should form a convention/standard for tags?

**Comment by TicClick** [comment]
I don't see any kind of a convention or standard possible here -- tags are phrases/words you can imagine people will use if they expect to find the article on top of the search results page

similarly, if an article doesn't have any tags, it's alright -- meaning, there isn't an apt combination of words to describe it (AND which people would use when searching -- this is important)

I didn't comment on this issue so far (even though I was aware of it having being created) precisely because of that.

regarding Chinese, it's probably a tricky case which needs to reported to the web team instead (poor search performance on languages that don't separate words by spaces)

**Comment by TicClick** [comment]
closing this since it sounds like a general cleanup idea rather than a specific issue with concrete articles (besides the follow-up bug is filed already)
